# Generated by Django 4.2.18 on 2025-01-17 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatBot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admission',
            table='Admission',
        ),
        migrations.AlterModelTable(
            name='chatbotresponse',
            table='ChatbotResponse',
        ),
        migrations.AlterModelTable(
            name='chatlog',
            table='ChatLog',
        ),
        migrations.AlterModelTable(
            name='contact',
            table='Contact',
        ),
        migrations.AlterModelTable(
            name='course',
            table='Course',
        ),
    ]
