# Generated by Django 4.2.18 on 2025-01-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatBot', '0002_alter_admission_table_alter_chatbotresponse_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem1', models.IntegerField()),
                ('sem2', models.IntegerField()),
                ('sem3', models.IntegerField()),
                ('sem4', models.IntegerField()),
                ('sem5', models.IntegerField()),
                ('sem6', models.IntegerField()),
                ('sem7', models.IntegerField()),
                ('sem8', models.IntegerField()),
            ],
            options={
                'db_table': 'Fees',
            },
        ),
    ]
