# Generated by Django 4.2.18 on 2025-01-18 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatBot', '0003_fees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fees',
            name='sem7',
        ),
        migrations.RemoveField(
            model_name='fees',
            name='sem8',
        ),
    ]
