# Generated by Django 4.2.18 on 2025-01-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatBot', '0004_remove_fees_sem7_remove_fees_sem8'),
    ]

    operations = [
        migrations.CreateModel(
            name='chatBot_querries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=555)),
            ],
            options={
                'db_table': 'chatbot_querries',
            },
        ),
    ]
