# Generated by Django 4.2.18 on 2025-01-31 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatBot', '0005_chatbot_querries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotresponse',
            name='response',
            field=models.TextField(verbose_name=10000),
        ),
    ]
