# Generated by Django 4.2.18 on 2025-02-06 15:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chatBot', '0007_alter_chatlog_age_alter_chatlog_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatlog',
            old_name='query',
            new_name='bot_response',
        ),
        migrations.RenameField(
            model_name='chatlog',
            old_name='response',
            new_name='user_query',
        ),
        migrations.RemoveField(
            model_name='chatlog',
            name='age',
        ),
        migrations.RemoveField(
            model_name='chatlog',
            name='email',
        ),
        migrations.RemoveField(
            model_name='chatlog',
            name='name',
        ),
        migrations.RemoveField(
            model_name='chatlog',
            name='phone',
        ),
        migrations.AddField(
            model_name='chatlog',
            name='session_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='chatlog',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
