# Generated by Django 4.2.18 on 2025-02-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatBot', '0008_rename_query_chatlog_bot_response_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('mother_tongue', models.CharField(choices=[('malayalam', 'Malayalam'), ('hindi', 'Hindi'), ('english', 'English'), ('bengali', 'Bengali'), ('marathi', 'Marathi'), ('telugu', 'Telugu'), ('tamil', 'Tamil'), ('gujarati', 'Gujarati'), ('urdu', 'Urdu'), ('kannada', 'Kannada'), ('odia', 'Odia'), ('punjabi', 'Punjabi'), ('assamese', 'Assamese'), ('maithili', 'Maithili'), ('sanskrit', 'Sanskrit'), ('konkani', 'Konkani'), ('tulu', 'Tulu')], max_length=20)),
                ('nationality', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('fathers_guardians_mobile_number', models.CharField(max_length=15)),
                ('admission_for', models.CharField(max_length=100)),
                ('academic_year', models.CharField(max_length=9)),
                ('priority_1', models.CharField(choices=[('bca', 'Bachelor of Science in Computer Science'), ('ba_eng', 'Bachelor of Arts in English Literature'), ('bcom', 'Bachelor of Commerce'), ('bba', 'Bachelor of Business Administration'), ('bsc_phy', 'Bachelor of Science in Physics')], max_length=20)),
                ('priority_2', models.CharField(choices=[('bca', 'Bachelor of Science in Computer Science'), ('ba_eng', 'Bachelor of Arts in English Literature'), ('bcom', 'Bachelor of Commerce'), ('bba', 'Bachelor of Business Administration'), ('bsc_phy', 'Bachelor of Science in Physics')], max_length=20)),
                ('priority_3', models.CharField(choices=[('bca', 'Bachelor of Science in Computer Science'), ('ba_eng', 'Bachelor of Arts in English Literature'), ('bcom', 'Bachelor of Commerce'), ('bba', 'Bachelor of Business Administration'), ('bsc_phy', 'Bachelor of Science in Physics')], max_length=20)),
                ('admission_quota', models.CharField(choices=[('management', 'Management Quota'), ('nri', 'NRI')], max_length=20)),
                ('tenth_board', models.CharField(choices=[('hse_kerala', 'HSE KERALA'), ('cbse', 'CBSE'), ('icse', 'ICSE'), ('others', 'OTHERS')], max_length=20)),
                ('tenth_register_number', models.CharField(max_length=50)),
                ('tenth_year_of_passing', models.CharField(max_length=4)),
                ('tenth_total_score', models.IntegerField()),
                ('sslc_percentage', models.FloatField()),
                ('higher_secondary_school_name', models.CharField(max_length=200)),
                ('higher_secondary_board', models.CharField(choices=[('hse_kerala', 'HSE KERALA'), ('cbse', 'CBSE'), ('icse', 'ICSE'), ('others', 'OTHERS')], max_length=20)),
                ('higher_secondary_year_of_passing', models.CharField(max_length=4)),
                ('physics_percentage', models.FloatField(blank=True, null=True)),
                ('chemistry_percentage', models.FloatField(blank=True, null=True)),
                ('maths_percentage', models.FloatField(blank=True, null=True)),
                ('computer_science_percentage', models.FloatField(blank=True, null=True)),
                ('total_percentage', models.FloatField()),
            ],
        ),
    ]
