# Generated by Django 4.2.18 on 2025-02-07 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatBot', '0009_applications'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='applications',
            table='applications',
        ),
        migrations.AlterModelTable(
            name='chatlog',
            table='chatLog',
        ),
    ]
