# Generated by Django 4.2.18 on 2025-02-07 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatBot', '0011_applicant'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='applicant',
            table='applicants',
        ),
    ]
