# Generated by Django 4.2.18 on 2025-02-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatBot', '0012_alter_applicant_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='applicant_id',
            field=models.CharField(blank=True, max_length=10001, null=True),
        ),
    ]
