# Generated by Django 4.2.18 on 2025-02-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatBot', '0014_applications_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='application_number',
            field=models.CharField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='applicant_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
