# Generated by Django 4.2.18 on 2025-02-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatBot', '0015_applications_application_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='application_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
