# Generated by Django 4.2.18 on 2025-02-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatBot', '0016_alter_applications_application_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=225, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'management',
            },
        ),
        migrations.RemoveField(
            model_name='applications',
            name='application_number',
        ),
    ]
