# Generated by Django 4.2.18 on 2025-02-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatBot', '0017_collegemanagement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='application_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
