# Generated by Django 4.2.18 on 2025-02-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatBot', '0018_applications_application_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='alloted_course',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='seats',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
