# Generated by Django 4.2.18 on 2025-02-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatBot', '0020_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tag',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
