# Generated by Django 4.2.18 on 2025-03-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatBot', '0021_course_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='applicant_photo',
            field=models.ImageField(blank=True, null=True, upload_to='applicant_photos/'),
        ),
        migrations.AddField(
            model_name='applications',
            name='tenth_mark_list',
            field=models.ImageField(blank=True, null=True, upload_to='tenth_mark_lists/'),
        ),
        migrations.AddField(
            model_name='applications',
            name='twelfth_mark_list',
            field=models.ImageField(blank=True, null=True, upload_to='twelfth_mark_lists/'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10, null=True),
        ),
    ]
