# Generated by Django 4.2.18 on 2025-03-07 06:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatBot', '0023_paymentmethod_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applications',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
