# Generated by Django 4.2.18 on 2025-04-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatBot', '0024_applications_created_at_applications_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminderId', models.IntegerField()),
                ('reminder', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'reminder',
            },
        ),
        migrations.AddField(
            model_name='applicant',
            name='notification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
