# Generated by Django 4.2.18 on 2025-03-18 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatBot', '0025_reminder'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reminder',
            table='reminder',
        ),
    ]
