# Generated by Django 4.2.18 on 2025-03-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatBot', '0026_alter_reminder_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='notification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
