# Generated by Django 4.2.18 on 2025-04-23 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatBot', '0025_reminder_applicant_notification_delete_payment_and_more'),
        ('chatBot', '0027_applicant_notification'),
    ]

    operations = [
    ]
