# Generated by Django 4.2.18 on 2025-04-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatBot', '0028_merge_20250423_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='notification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
